using System;
using System.Reflection;
using System.Diagnostics;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Linq;

using Barotrauma;
using HarmonyLib;
using BaroJunk;

namespace JovianRadiationRework
{
  public class EnabledModels : IConfig
  {
    #region Autogenerated
    // public bool VanillaRadiationModel { get; set; } = true;
    public bool AmbientLightModel { get; set; } = true;
    public bool RadProtectionUpgradesModel { get; set; } = true;
    public bool IndoorProtectionModel { get; set; } = true;
    public bool HuskRadiationResistanceModel { get; set; } = true;
    public bool DepthBasedDamageModel { get; set; } = true;
    public bool SmoothRadiationProgressModel { get; set; } = true;
    public bool CustomMapRadiationDrawerModel { get; set; } = true;
    public bool SmoothLocationTransformerModel { get; set; } = true;
    public bool MoreMonstersModel { get; set; } = true;
    public bool DamageToElectronicsModel { get; set; } = true;
    public bool CustomMonsterDamagerModel { get; set; } = true;
    public bool CustomCharacterDamagerModel { get; set; } = true;
    public bool CustomRadiationUpdaterModel { get; set; } = true;
    public bool AdditionalMetadataSetterModel { get; set; } = true;
    public bool AdvanceOnSaveAndQuitModel { get; set; } = true;
    public bool CustomTooltipModel { get; set; } = true;
    #endregion

    public EnabledModels()
    {
      this.OnPropChanged((key, value) =>
      {
        Mod.ModelManager.SetModelState(key, (bool)value);
      });

      this.OnUpdated(() => Mod.ModelManager.SyncModelStates(this));
    }
  }
}